version: "{build}"

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9

matrix:
  fast_finish: true

cache:
  - node_modules
  - flow-typed

services:
  - mongodb

platform: x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i
  - npm run flow-typed
  - set PATH=C:\mongodb\server\3.2\bin;%PATH%

build_script:
  - npm run build

test_script:
  - npm run lint
  - npm run flow -- check
  - npm run test

after_test:
  - npm run docs

artifacts:
  - path: build
  - path: coverage\lcov-report
    name: coverage
  - path: docs
