version: "{build}"

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9

matrix:
  fast_finish: true

cache:
  - node_modules
  - flow-typed

services:
  - mongodb

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i
  - npm run flow-typed

build_script:
  - npm run build

test_script:
  - npm run lint
  - npm run flow
  - npm run test

after_test:
  - npm run docs

artifacts:
  - path: build
  - path: coverage\lcov-report
    name: coverage
  - path: docs
